name: Build and Deploy Slovnik

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
    
jobs:
  build-and-deploy:
    name: Build and Deploy Applications
    runs-on: fedora
    steps:
      - name: Checkout code
        run: |
          git clone https://git.lynder.dev/foxdefacto/Preklady.git .
          git checkout ${{ github.sha }}
      
      - name: Build Frontend Docker Image
        run: |
          cd slovnik-frontend
          podman build -t localhost:5000/slovnik-frontend:latest -f Dockerfile .
      
      - name: Build Backend Docker Image
        run: |
          cd slovnik-backend
          podman build -t localhost:5000/slovnik-backend:latest -f Dockerfile .
          
      - name: Push Frontend Image to Local Registry
        run: podman push localhost:5000/slovnik-frontend:latest
      
      - name: Push Backend Image to Local Registry
        run: podman push localhost:5000/slovnik-backend:latest

      - name: Stop Running Services
        run: |
          sudo systemctl stop frontend.service
          sudo systemctl stop backend.service

      - name: Deploy New Services
        run: |
          podman pull localhost:5000/slovnik-frontend:latest
          podman pull localhost:5000/slovnik-backend:latest
          sudo systemctl start backend.service
          sudo systemctl start frontend.service
