name: Build and Deploy Slovnik

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
    
jobs:
  build-and-deploy:
    name: Build and Deploy Applications
    runs-on: fedora
    steps:
      - name: Checkout code
        run: |
          git clone https://git.lynder.dev/foxdefacto/Preklady.git .
          git checkout ${{ github.sha }}
          
      - name: Build Frontend Docker Image
        run: |
          cd slovnik-frontend
          podman build -t localhost:5000/slovnik-frontend:latest -f Dockerfile .
          
    #  - name: Build Backend Docker Image
     #   run: |
      #    cd slovnik-backend
       #   podman build -t localhost:5000/slovnik-backend:latest -f Dockerfile .
          
      - name: Push Images to Local Registry
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
        run: |
          podman push localhost:5000/slovnik-frontend:latest
        #  podman push localhost:5000/slovnik-backend:latest
          
      - name: Stop Running Services
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
        run: |
          sudo systemctl stop slovnik-frontend.service
         # sudo systemctl stop slovnik-backend.service
          
      - name: Deploy New Services
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
        run: |
          podman pull localhost:5000/slovnik-frontend:latest
        #  podman pull localhost:5000/slovnik-backend:latest
          
          # Zkontrolujte, zda služby běží
          sudo systemctl status slovnik-frontend.service
          sudo systemctl status slovnik-backend.service